import { ClientProfile, UnifiedAdRecord, CreativeIntelligence, LandingPageAnalysis, ExperimentItem, HistoricalAnalysisRun } from './types';

export const DEMO_CLIENT_ANKIT: ClientProfile = {
  id: 'client-ankit-batra',
  name: 'Ankit Batra',
  businessName: 'ScaleGrowth Consulting & Mastermind',
  website: 'https://ankitbatra.io/growth-accelerator',
  productService: '8-Week B2B Performance Marketing & Funnel Architecture Accelerator',
  mainOffer: 'Book a 1-on-1 Growth Blueprint Call ($500 Value, Free for qualified founders doing >$20k MRR)',
  targetAudience: 'B2B Founders, CMOs, Agency Owners, and Performance Marketing Leads looking to scale paid acquisition past $50k/mo profitably without burning cash on unvalidated creatives.',
  geography: 'India, United States, UAE, United Kingdom, Singapore',
  usp: 'Proprietary Creative-Led Growth Framework combining multimodal creative testing with real-time attribution, trained directly on 250+ audited client funnels.',
  painPoints: [
    'Rising Meta CPA/CPL and erratic ad performance after scaling budget past ₹10k/day',
    'Ad fatigue within 4-5 days of launching new creatives',
    'High click-through rate (CTR) but severe drop-off on landing page and booking form',
    'Creative agencies delivering pretty videos that generate zero pipeline or qualified leads',
    'Lack of systematic creative iteration workflow based on hook & hold rates'
  ],
  desires: [
    'Predictable, scalable CAC below ₹450 / $18 per qualified sales call',
    'A repeatable creative machine that outputs winning hooks and angle variations weekly',
    'Consistent ROAS above 3.5x on mid-ticket and high-ticket B2B offerings',
    'Full transparency into what hook and angle drove the revenue'
  ],
  customerObjections: [
    'Is this just another generic course or agency template?',
    'Will this work in high-CPM US/UK markets or only local Indian traffic?',
    'We already have an in-house media buyer; why do we need this advisory?',
    'How much creative production budget do we need to test these hooks?'
  ],
  competitors: [
    'Reforge Growth Series',
    'Foundr Masterclasses',
    'HyperScale Media Agency',
    'AdWorld B2B Blueprint'
  ],
  brandTone: 'Direct, Analytical, No-BS, Data-Backed, Authoritative, High-Energy yet Professional',
  approvedClaims: [
    'Audited over ₹12Cr ($1.5M+) in Meta & Google ad spend',
    'Average client reduces CAC by 28% in first 21 days of hook restructuring',
    'Proprietary 7-point Creative + LP Message Match scoring protocol'
  ],
  restrictedClaims: [
    'Do not guarantee "10x ROI in 7 days"',
    'Never claim Meta algorithms are "broken or hacked"',
    'Avoid spammy clickbait claims like "Get rich with zero ad spend"'
  ],
  metaConnected: true,
  metaAccountId: 'act_49201948201',
  lastAnalysisDate: '2026-09-18',
  activeExperimentsCount: 4,
  currency: 'INR'
};

export const DEMO_CLIENT_ECOMMERCE: ClientProfile = {
  id: 'client-lumina-skincare',
  name: 'Lumina Dermal Labs',
  businessName: 'Lumina Clinical Skincare',
  website: 'https://luminaskin.com/peptide-barrier-repair',
  productService: 'Dermatologist-Formulated Barrier Repair Ceramide & Copper Peptide Serum',
  mainOffer: 'Buy 1 Get 1 40% Off + Free HydraMist on prepaid orders over ₹1,999',
  targetAudience: 'Women & Men aged 24-42 suffering from compromised skin barriers, redness, breakouts, and chemical peel damage.',
  geography: 'India (Tier 1 & 2 Metros), UAE',
  usp: 'Micro-encapsulated copper peptides with clinical 72-hour moisture retention and zero synthetic fragrance.',
  painPoints: [
    'Skin breakouts triggered by harsh actives and pollution',
    'Products feeling sticky or causing pilling under sunscreen',
    'Spending thousands on luxury creams with zero visible change in redness'
  ],
  desires: [
    'Calm, glowing skin in under 14 days without dermat prescription',
    'Fast-absorbing clean serum backed by clinical trial data'
  ],
  customerObjections: [
    'Will it cause purging or fungal acne?',
    'Why is it priced higher than mass-market pharmacy serums?'
  ],
  competitors: ['Minimalist', 'The Ordinary', 'Dr. Sheth', 'Paula Choice'],
  brandTone: 'Clean, Scientific, Empathetic, Reassuring, Premium Minimalist',
  approvedClaims: ['94% saw reduced redness in 7 days (clinical trial n=120)', 'Dermatologist tested & Non-comedogenic'],
  restrictedClaims: ['Do not claim to cure medical cystic acne or eczema'],
  metaConnected: false,
  lastAnalysisDate: '2026-09-15',
  activeExperimentsCount: 2,
  currency: 'INR'
};

export const DEMO_CLIENT_MKR: ClientProfile = {
  id: 'client-mkr-audit',
  name: 'Dr. Ankiit Btra',
  businessName: 'Dr. Ankiit Btra Astro & Numerology',
  website: 'https://thebatraanumerology.org/master-kundali-fb2/',
  productService: 'Kundali report',
  mainOffer: 'Express delivery / special ebooks (Pricing: 499 / exp delivery +149 / ebook - +49)',
  pricing: '499',
  targetAudience: '23+ men / women (Performing gender: MALE 70-80% conversions)',
  geography: 'India (Pan-India Metro & Tier 1/2)',
  usp: 'Personalised kundali, brand trust',
  painPoints: [
    'Ad fatigue on high-spend CBO winner stacks (MKR-73 & MKR-74 at 0.60x ROAS)',
    'Budget leaks on unconverting variants (MKR_AB_VS-52B: ₹3,274 spent, 0 sales)',
    'Under-allocated budget on high-performing breakout creatives (MKR-77, 78 & VS-32 DP)'
  ],
  desires: [
    'Consistently maintain CPA under ₹350 on top-of-funnel campaigns',
    'Scale account spend profitably above 2.0x blended ROAS',
    'Reallocate budget rapidly from fatigued creative stacks to high-ROAS hooks'
  ],
  customerObjections: [
    'Is the offer compelling enough on mobile landing page?',
    'Delay in report delivery causing customer anxiety'
  ],
  competitors: ['Market leaders in online astrology & kundali reports'],
  brandTone: 'Punchy, Fast-Paced Direct Response, High-Contrast UGC & Video Consultations',
  approvedClaims: ['100% Personalised Guidance & Simple Remedies', 'Detailed Life Predictions (Career, Wealth, Relationships)'],
  restrictedClaims: ['No superstitious guarantees', 'Avoid false timeline commitments'],
  metaConnected: false,
  lastAnalysisDate: '2026-09-28',
  activeExperimentsCount: 4,
  currency: 'INR',
  driveVideoFolderUrl: 'https://drive.google.com/drive/folders/mkr_videos',
  pastLearnings: [
    { test: 'Added ebook & express delivery to improve AOV', learning: 'It was successful and increased overall revenue' },
    { test: 'We started with old pixel with better learning', learning: 'Not successful, as it was over reporting and lot of discrepancy issues' },
    { test: 'Tested new pixel', learning: 'Discrepancy reduced and reporting got improved' },
    { test: 'Tested multiple creative styles - celeb clips from YT', learning: 'Not successful & scalable' }
  ],
  primaryTexts: [
    "1. Aapki mehnat ke bawajood career mein progress nahi ho rahi? Ya marriage mein baar-baar delays aa rahe hain? Problem aap mein nahi, shayad aapke grah-nakshatro ke sahi timing mein hai! 🌌\n\nDr. Ankiit Btra ki Master Kundali Report se jaaniye aapke 7th house, Rahu-Ketu ke prabhav, aur simple remedies jo aapki life ki rukaavaton ko door kar sakti hain. ✨\n\n✅ Detailed Life Predictions (Career, Wealth, Relationships)\n✅ Easy-to-understand Remedies\n✅ Personal Guidance\n\n👉 Apni personalized Master Kundali Report aaj hi order karein! 🔮",
    "2. Career set tha, earning achhi thi... par shaadi 33 ki age tak nahi ho rahi thi. 😔\n\nJab unhone Dr. Ankiit Btra se apni Kundali analyse karwayi, toh pata chala 7th house par Rahu aur Jupiter weak hone ki wajah se delay ho raha tha. Kuch simple remedies follow ki aur 3-4 mahine mein shaadi fix ho gayi! 💍✨\n\nAap bhi apni zindagi ke hidden grah dosh aur unke aasan upaay jaan sakte hain.\n\n📜 Order your Master Kundali Report today and unlock your path to success & happiness! 🙏",
    "3. Aapka sahi waqt kab aayega? ⏳\n\nJaaniye apne Career, Wealth, Marriage aur Health ke Secret Predictions Dr. Ankiit Btra ki Master Kundali Report se! 🔮\n\n⚡ Easy Remedies | 🎯 Accurate Insights | 📜 Personalized PDF Report\n\n👇 Niche diye gaye link par click karke abhi order karein! 🚀"
  ],
  headlines: [
    'Get life clarity with Master Kundali Report',
    'Delay In Marriage & Career? Find Remedies Now 💍✨',
    'Get Your Master Kundali Report Today! 📜⚡'
  ],
  descriptions: [
    'Career, Wealth & Relationship Predictions By Ankiit Btra',
    '100% Personalised Guidance & Simple Remedies'
  ],
  ctas: ['Order Now'],
  audienceInsights: 'Winner : Open | 23-65+ | All genders | But performing gender here is MALE (70-80% conversions)'
};

export const INITIAL_CLIENTS: ClientProfile[] = [
  DEMO_CLIENT_MKR,
  DEMO_CLIENT_ANKIT,
  DEMO_CLIENT_ECOMMERCE
];

export const DEMO_AD_RECORDS_ANKIT: UnifiedAdRecord[] = [
  {
    clientId: 'client-ankit-batra',
    platform: 'meta',
    account: 'Ankit Batra Growth',
    campaign: 'TOF_Scale_DirectResponse_Video_Q3',
    adSet: 'Broad_Interest_B2B_Founders_35kSpend',
    adName: 'AB_V1_ProblemHook_StopWastingBudget_UGC',
    adId: 'ad_90124801',
    date: '2026-09-18',
    objective: 'LEADS',
    spend: 18450,
    impressions: 218400,
    reach: 165200,
    clicks: 7420,
    ctr: 3.40,
    cpc: 2.49,
    cpm: 84.48,
    landingPageViews: 6180,
    leads: 186,
    purchases: 0,
    conversions: 186,
    conversionRate: 3.01,
    cpl: 99.19,
    cpa: 99.19,
    revenue: 93000,
    roas: 5.04,
    primaryText: "If your Meta CPA doubled this month, stop touching your bidding strategy. In 90% of the 250+ client accounts we audited, the bleed isn't your targeting—it's your first 3 seconds.\n\nHere is the exact Creative-Led Funnel framework we use to generate high-intent B2B discovery calls under ₹120 consistently.",
    headline: "Why Your B2B Ads Bleed Cash (And The 3-Second Fix)",
    description: "Download the 7-Point Creative Audit Checklist & Framework",
    cta: "Book Now",
    creativeId: 'cr_vid_01',
    creativeUrl: 'https://storage.googleapis.com/ad-analyser-assets/ankit_ugc_hook1.mp4',
    driveUrl: 'https://drive.google.com/file/d/1B7x9A4K8mQp_DemoHookProblem/view?usp=sharing',
    landingPageUrl: 'https://ankitbatra.io/growth-accelerator?utm_source=meta&utm_content=v1_problem',
    tier: 'Strong Performer',
    tierScore: 94,
    tierReasoning: [
      'ROAS of 5.04x exceeds account average (3.2x) by +57%',
      'Exceptional CPL of ₹99.19 vs. benchmark target ₹150 (-34% cheaper)',
      'High volume (186 leads) on healthy ₹18,450 spend'
    ],
    evidence: [
      'Problem-led hook in first 2 seconds immediately interrupts founder audience',
      'Strong message match between ad headline and LP hero section',
      'High Click-to-LP view ratio (83.3%) confirms zero page-load drop-off'
    ]
  },
  {
    clientId: 'client-ankit-batra',
    platform: 'meta',
    account: 'Ankit Batra Growth',
    campaign: 'TOF_Scale_DirectResponse_Video_Q3',
    adSet: 'Broad_Interest_B2B_Founders_35kSpend',
    adName: 'AB_V2_FounderBreakdown_WhiteboardMath',
    adId: 'ad_90124802',
    date: '2026-09-18',
    objective: 'LEADS',
    spend: 14200,
    impressions: 162000,
    reach: 124000,
    clicks: 5350,
    ctr: 3.30,
    cpc: 2.65,
    cpm: 87.65,
    landingPageViews: 4410,
    leads: 132,
    purchases: 0,
    conversions: 132,
    conversionRate: 2.99,
    cpl: 107.57,
    cpa: 107.57,
    revenue: 66000,
    roas: 4.65,
    primaryText: "Most agencies blame iOS updates or Meta algorithms when CAC spikes. Let's do the actual unit economics on a whiteboard:\n\nIf your CAC is ₹800 and your average deal size is ₹40,000, you don't need cheaper traffic. You need higher-intent creative qualification.\n\nWatch how we restructured this exact B2B funnel.",
    headline: "The Simple Whiteboard Math That Halved Our Client CAC",
    description: "Free Case Study Video Breakdown (No Fluff)",
    cta: "Learn More",
    creativeId: 'cr_vid_02',
    creativeUrl: 'https://storage.googleapis.com/ad-analyser-assets/ankit_whiteboard_v2.mp4',
    driveUrl: 'https://drive.google.com/file/d/1C9z7M2L6vXp_DemoWhiteboardMath/view?usp=sharing',
    landingPageUrl: 'https://ankitbatra.io/growth-accelerator?utm_source=meta&utm_content=v2_whiteboard',
    tier: 'Strong Performer',
    tierScore: 91,
    tierReasoning: [
      'Strong ROAS of 4.65x with ₹107.57 CPL',
      'Solid lead volume (132 leads) and high CTR (3.30%)',
      'Consistent daily conversion velocity with zero spend spikes'
    ],
    evidence: [
      'Founder authority and educational format builds immediate credibility',
      'Direct mathematical breakdown addresses skepticism before click'
    ]
  },
  {
    clientId: 'client-ankit-batra',
    platform: 'meta',
    account: 'Ankit Batra Growth',
    campaign: 'TOF_Scale_DirectResponse_Video_Q3',
    adSet: 'Agency_Owners_Lookalikes_20kSpend',
    adName: 'AB_V3_CaseStudy_TestimonialReel_ScaleStory',
    adId: 'ad_90124803',
    date: '2026-09-18',
    objective: 'LEADS',
    spend: 9600,
    impressions: 110400,
    reach: 89000,
    clicks: 3410,
    ctr: 3.09,
    cpc: 2.81,
    cpm: 86.95,
    landingPageViews: 2820,
    leads: 81,
    purchases: 0,
    conversions: 81,
    conversionRate: 2.87,
    cpl: 118.52,
    cpa: 118.52,
    revenue: 40500,
    roas: 4.22,
    primaryText: "\"We went from ₹1,400 CPL to under ₹190 in 14 days by stripping away fancy agency videos.\" — Rohan, Founder of DevScale SaaS.\n\nRead the complete case study and how you can deploy the exact same creative testing pipeline for your agency or SaaS.",
    headline: "How DevScale Slashed CPL by 86% in 14 Days",
    description: "Verified Client Case Study & Funnel Breakdown",
    cta: "Sign Up",
    creativeId: 'cr_vid_03',
    creativeUrl: 'https://storage.googleapis.com/ad-analyser-assets/ankit_testimonial_v3.mp4',
    driveUrl: 'https://drive.google.com/file/d/1D4k8N9O3tYq_DemoTestimonialScale/view?usp=sharing',
    landingPageUrl: 'https://ankitbatra.io/growth-accelerator?utm_source=meta&utm_content=v3_casestudy',
    tier: 'Promising',
    tierScore: 82,
    tierReasoning: [
      'ROAS of 4.22x is well above target (>3.0x)',
      'Good CPL at ₹118.52 with 81 leads generated',
      'Requires budget scaling to test fatigue resistance at >₹25k spend'
    ],
    evidence: [
      'Social proof testimonial overcomes "will this work for me" objection',
      'Specific numbers in headline (86% reduction, 14 days) generate high credibility'
    ]
  },
  {
    clientId: 'client-ankit-batra',
    platform: 'meta',
    account: 'Ankit Batra Growth',
    campaign: 'MOFU_Retargeting_HighIntent_Q3',
    adSet: 'Website_Visitors_30d_VideoViewers_50pct',
    adName: 'AB_V4_Static_ChecklistInfographic_7Steps',
    adId: 'ad_90124804',
    date: '2026-09-18',
    objective: 'LEADS',
    spend: 6800,
    impressions: 74500,
    reach: 52000,
    clicks: 2280,
    ctr: 3.06,
    cpc: 2.98,
    cpm: 91.27,
    landingPageViews: 1910,
    leads: 59,
    purchases: 0,
    conversions: 59,
    conversionRate: 3.09,
    cpl: 115.25,
    cpa: 115.25,
    revenue: 29500,
    roas: 4.34,
    primaryText: "Before you spend another ₹10,000 on Meta ads, run your campaign through this 7-Point Pre-Launch Checklist.\n\n1. Hook-to-headline verbatim match\n2. Single core problem statement\n3. Proof before 5 seconds\n4. Zero form friction\n\nDownload the full high-res PDF infographic free.",
    headline: "The 7-Point Pre-Launch Creative Checklist (PDF)",
    description: "Instant Free Download for Growth Teams",
    cta: "Download",
    creativeId: 'cr_img_01',
    creativeUrl: 'https://storage.googleapis.com/ad-analyser-assets/ankit_static_infographic.png',
    driveUrl: 'https://drive.google.com/file/d/1E8m2L5P9rZv_DemoInfographicChecklist/view?usp=sharing',
    landingPageUrl: 'https://ankitbatra.io/growth-accelerator?utm_source=meta&utm_content=v4_infographic',
    tier: 'Promising',
    tierScore: 80,
    tierReasoning: [
      'High conversion rate (3.09%) in retargeting segment',
      'Low CPL of ₹115.25 and 4.34x ROAS',
      'Static creative format provides cost-effective diversification against video fatigue'
    ],
    evidence: [
      'High contrast visual design with readable step numbers',
      'Clear tangible utility (PDF checklist) drives low-friction opt-ins'
    ]
  },
  {
    clientId: 'client-ankit-batra',
    platform: 'meta',
    account: 'Ankit Batra Growth',
    campaign: 'TOF_Scale_DirectResponse_Video_Q3',
    adSet: 'Broad_Interest_B2B_Founders_35kSpend',
    adName: 'AB_V5_Contrarian_StopHiringAgencies_Rant',
    adId: 'ad_90124805',
    date: '2026-09-18',
    objective: 'LEADS',
    spend: 8900,
    impressions: 98000,
    reach: 78000,
    clicks: 2540,
    ctr: 2.59,
    cpc: 3.50,
    cpm: 90.81,
    landingPageViews: 2010,
    leads: 48,
    purchases: 0,
    conversions: 48,
    conversionRate: 2.39,
    cpl: 185.42,
    cpa: 185.42,
    revenue: 24000,
    roas: 2.70,
    primaryText: "Firing your marketing agency won't fix your customer acquisition if you have no in-house creative feedback loop. Here's why $10k/mo retainers are failing founders in 2026.",
    headline: "Why Most Agency Retainers Waste Your Budget",
    description: "Build an In-House Creative Engine Instead",
    cta: "Learn More",
    creativeId: 'cr_vid_05',
    creativeUrl: 'https://storage.googleapis.com/ad-analyser-assets/ankit_contrarian_v5.mp4',
    driveUrl: 'https://drive.google.com/file/d/1F2n7B6X3kLm_DemoContrarianAgency/view?usp=sharing',
    landingPageUrl: 'https://ankitbatra.io/growth-accelerator?utm_source=meta&utm_content=v5_contrarian',
    tier: 'Average',
    tierScore: 64,
    tierReasoning: [
      'ROAS of 2.70x is below target account hurdle (3.0x)',
      'CPL of ₹185.42 is +87% higher than top performers (₹99.19)',
      'CTR is moderate (2.59%) with higher CPC (₹3.50)'
    ],
    evidence: [
      'Contrarian angle polarizes audience but fails to clearly transition to the accelerator offer',
      'Landing page headline does not match the anti-agency narrative, causing drop-off'
    ],
    rootCause: 'Copy',
    recommendedTest: 'Refine transition script from grievance to solution; test matching dedicated landing page'
  },
  {
    clientId: 'client-ankit-batra',
    platform: 'meta',
    account: 'Ankit Batra Growth',
    campaign: 'TOF_Scale_DirectResponse_Video_Q3',
    adSet: 'Broad_Interest_B2B_Founders_35kSpend',
    adName: 'AB_V6_Generic_GrowthMasterclass_StockVideo',
    adId: 'ad_90124806',
    date: '2026-09-18',
    objective: 'LEADS',
    spend: 11200,
    impressions: 142000,
    reach: 110000,
    clicks: 1980,
    ctr: 1.39,
    cpc: 5.66,
    cpm: 78.87,
    landingPageViews: 1320,
    leads: 28,
    purchases: 0,
    conversions: 28,
    conversionRate: 2.12,
    cpl: 400.00,
    cpa: 400.00,
    revenue: 14000,
    roas: 1.25,
    primaryText: "Join our exclusive growth masterclass to learn proven strategies to scale your revenue and master digital marketing across all channels in 2026.",
    headline: "Scale Your Business With Proven Digital Marketing",
    description: "Register Today for the Online Session",
    cta: "Sign Up",
    creativeId: 'cr_vid_06',
    creativeUrl: 'https://storage.googleapis.com/ad-analyser-assets/ankit_stock_generic_v6.mp4',
    driveUrl: 'https://drive.google.com/file/d/1G8x3M9Q2bWv_DemoGenericStockMasterclass/view?usp=sharing',
    landingPageUrl: 'https://ankitbatra.io/growth-accelerator?utm_source=meta&utm_content=v6_generic',
    tier: 'Underperforming',
    tierScore: 28,
    tierReasoning: [
      'Severe underperformance: CPL of ₹400.00 is 4x higher than top performers (₹99.19)',
      'Dismal ROAS of 1.25x resulting in negative unit economics after operational costs',
      'Extremely poor CTR (1.39%) with elevated CPC (₹5.66)'
    ],
    evidence: [
      'Generic stock video footage of people smiling in an office creates zero pattern interrupt',
      'Vague, buzzword-heavy copy ("scale revenue", "proven digital marketing") lacks specificity',
      'High spend (₹11,200) without statistical recovery indicates creative fatigue from day 1'
    ],
    rootCause: 'Creative',
    recommendedTest: 'Pause immediately. Replace stock footage with raw founder talking head + problem hook.'
  },
  {
    clientId: 'client-ankit-batra',
    platform: 'meta',
    account: 'Ankit Batra Growth',
    campaign: 'TOF_Scale_DirectResponse_Video_Q3',
    adSet: 'Agency_Owners_Lookalikes_20kSpend',
    adName: 'AB_V7_FeatureDump_CurriculumBulletPoints_Graphic',
    adId: 'ad_90124807',
    date: '2026-09-18',
    objective: 'LEADS',
    spend: 7800,
    impressions: 89000,
    reach: 67000,
    clicks: 1410,
    ctr: 1.58,
    cpc: 5.53,
    cpm: 87.64,
    landingPageViews: 920,
    leads: 21,
    purchases: 0,
    conversions: 21,
    conversionRate: 2.28,
    cpl: 371.43,
    cpa: 371.43,
    revenue: 10500,
    roas: 1.35,
    primaryText: "Our 8-Week Accelerator covers Module 1: Attribution, Module 2: Hook Testing, Module 3: Media Buying, Module 4: Landing Page CRO, Module 5: Offer Architecture, Module 6: Team Hiring.",
    headline: "Comprehensive 8-Week Growth Curriculum",
    description: "See the complete weekly syllabus",
    cta: "Learn More",
    creativeId: 'cr_img_07',
    creativeUrl: 'https://storage.googleapis.com/ad-analyser-assets/ankit_curriculum_graphic.png',
    driveUrl: 'https://drive.google.com/file/d/1H5t4K8P1yUz_DemoCurriculumGraphic/view?usp=sharing',
    landingPageUrl: 'https://ankitbatra.io/growth-accelerator?utm_source=meta&utm_content=v7_curriculum',
    tier: 'Underperforming',
    tierScore: 32,
    tierReasoning: [
      'Unprofitable CPL of ₹371.43 and 1.35x ROAS',
      'High post-click drop-off: only 65.2% of clicks reached LP view',
      'Low engagement CTR (1.58%)'
    ],
    evidence: [
      'Feature-dump graphic creates cognitive overload without selling the transformation or pain relief',
      'Audience does not care about "modules" until they believe the core premise'
    ],
    rootCause: 'Copy',
    recommendedTest: 'Reframe curriculum items as specific problems solved (e.g. "Fix CPL spikes" instead of "Module 1").'
  },
  {
    clientId: 'client-ankit-batra',
    platform: 'meta',
    account: 'Ankit Batra Growth',
    campaign: 'TOF_Scale_DirectResponse_Video_Q3',
    adSet: 'Broad_Interest_B2B_Founders_35kSpend',
    adName: 'AB_V8_MismatchedLP_ScalePast50k_OfferDiscount',
    adId: 'ad_90124808',
    date: '2026-09-18',
    objective: 'LEADS',
    spend: 6400,
    impressions: 72000,
    reach: 56000,
    clicks: 2510,
    ctr: 3.49,
    cpc: 2.55,
    cpm: 88.89,
    landingPageViews: 2150,
    leads: 19,
    purchases: 0,
    conversions: 19,
    conversionRate: 0.88,
    cpl: 336.84,
    cpa: 336.84,
    revenue: 9500,
    roas: 1.48,
    primaryText: "Get our ₹50,000 Agency Scaling Template Pack for 90% off today only. Includes 50 winning Canva templates and swipe files.",
    headline: "90% Off Agency Scaling Template Bundle",
    description: "Limited Time Discount (Instant Access)",
    cta: "Get Offer",
    creativeId: 'cr_img_08',
    creativeUrl: 'https://storage.googleapis.com/ad-analyser-assets/ankit_discount_bundle.png',
    driveUrl: 'https://drive.google.com/file/d/1J9v2N4Q8rXw_DemoDiscountBundle/view?usp=sharing',
    landingPageUrl: 'https://ankitbatra.io/growth-accelerator?utm_source=meta&utm_content=v8_discount',
    tier: 'Underperforming',
    tierScore: 35,
    tierReasoning: [
      'Classic High CTR (3.49%) + Catastrophic Conversion Rate (0.88%) disconnect',
      'High CPL of ₹336.84 despite cheap clicks (₹2.55)',
      'Severe message match failure between discount template copy and consultation call LP'
    ],
    evidence: [
      'Ad promises a 90% off self-serve template pack, but landing page demands booking a 45-min consultation call',
      'Users bounce immediately upon realizing they must book a call rather than instant download'
    ],
    rootCause: 'Landing Page',
    recommendedTest: 'Fix landing page alignment: either create a 1-click checkout for templates or update ad to promise the Growth Blueprint Consultation.'
  },
  {
    clientId: 'client-ankit-batra',
    platform: 'meta',
    account: 'Ankit Batra Growth',
    campaign: 'TEST_NewHooks_FastPaced_Sep26',
    adSet: 'Broad_Testing_Sandbox_10kSpend',
    adName: 'AB_V9_TestHook_Audited12Crores_FastCuts',
    adId: 'ad_90124809',
    date: '2026-09-18',
    objective: 'LEADS',
    spend: 1850,
    impressions: 24500,
    reach: 19200,
    clicks: 980,
    ctr: 4.00,
    cpc: 1.89,
    cpm: 75.51,
    landingPageViews: 860,
    leads: 29,
    purchases: 0,
    conversions: 29,
    conversionRate: 3.37,
    cpl: 63.79,
    cpa: 63.79,
    revenue: 14500,
    roas: 7.84,
    primaryText: "I audited ₹12 Crores in Meta ad spend across 40 B2B niches in the last 12 months. Here are the ONLY 3 creative metrics that actually predicted profitability.",
    headline: "The 3 Creative Metrics That Actually Predict ROAS",
    description: "Data-driven breakdown from ₹12Cr in spend",
    cta: "Learn More",
    creativeId: 'cr_vid_09',
    creativeUrl: 'https://storage.googleapis.com/ad-analyser-assets/ankit_audited12cr_v9.mp4',
    driveUrl: 'https://drive.google.com/file/d/1K2m9P6X4wZq_DemoAudited12Cr/view?usp=sharing',
    landingPageUrl: 'https://ankitbatra.io/growth-accelerator?utm_source=meta&utm_content=v9_audited12cr',
    tier: 'Promising',
    tierScore: 89,
    tierReasoning: [
      'Outstanding preliminary ROAS of 7.84x and ₹63.79 CPL',
      'Exceptional CTR of 4.00% and high LP conversion rate (3.37%)',
      'Classified as Promising rather than Strong Performer due to preliminary spend (₹1,850 < ₹5,000 confidence threshold)'
    ],
    evidence: [
      'High-authority numbers hook (₹12 Crores, 40 niches) creates intense curiosity',
      'Immediate candidate for budget scale to ₹15,000 validation stage'
    ]
  },
  {
    clientId: 'client-ankit-batra',
    platform: 'meta',
    account: 'Ankit Batra Growth',
    campaign: 'TEST_NewHooks_FastPaced_Sep26',
    adSet: 'Broad_Testing_Sandbox_10kSpend',
    adName: 'AB_V10_TestHook_AIAssistantRant_MotionGraphic',
    adId: 'ad_90124810',
    date: '2026-09-18',
    objective: 'LEADS',
    spend: 420,
    impressions: 4800,
    reach: 4100,
    clicks: 110,
    ctr: 2.29,
    cpc: 3.82,
    cpm: 87.50,
    landingPageViews: 90,
    leads: 2,
    purchases: 0,
    conversions: 2,
    conversionRate: 2.22,
    cpl: 210.00,
    cpa: 210.00,
    revenue: 1000,
    roas: 2.38,
    primaryText: "AI won't replace performance marketers, but performance marketers who understand creative-first prompt architecture will replace everyone else.",
    headline: "Why AI Creative Prompts Fail Most Media Buyers",
    description: "Read the System Architecture Guide",
    cta: "Learn More",
    creativeId: 'cr_vid_10',
    creativeUrl: 'https://storage.googleapis.com/ad-analyser-assets/ankit_ai_rant_v10.mp4',
    driveUrl: 'https://drive.google.com/file/d/1L7x8M2P5rVz_DemoAIAssistantRant/view?usp=sharing',
    landingPageUrl: 'https://ankitbatra.io/growth-accelerator?utm_source=meta&utm_content=v10_ai_rant',
    tier: 'Insufficient Data',
    tierScore: 50,
    tierReasoning: [
      'Spend of ₹420 and 2 leads is far below statistical significance threshold',
      'Cannot draw conclusive winner/loser verdict until ad reaches at least ₹3,000 spend or 10+ leads'
    ],
    evidence: [
      'Early CTR is average (2.29%)',
      'Requires continued delivery before optimization decisions'
    ]
  },
  {
    clientId: 'client-ankit-batra',
    platform: 'meta',
    account: 'Ankit Batra Growth',
    campaign: 'TEST_NewHooks_FastPaced_Sep26',
    adSet: 'Broad_Testing_Sandbox_10kSpend',
    adName: 'AB_V11_TestImage_BrokenFunnelChart_DarkContrast',
    adId: 'ad_90124811',
    date: '2026-09-18',
    objective: 'LEADS',
    spend: 1250,
    impressions: 16000,
    reach: 13500,
    clicks: 560,
    ctr: 3.50,
    cpc: 2.23,
    cpm: 78.13,
    landingPageViews: 480,
    leads: 18,
    purchases: 0,
    conversions: 18,
    conversionRate: 3.75,
    cpl: 69.44,
    cpa: 69.44,
    revenue: 9000,
    roas: 7.20,
    primaryText: "Is your funnel leaking at Stage 2 or Stage 4? Look at this diagnostic chart. If your drop-off happens between click and LP view, fix your mobile page speed. If it happens between LP view and booking, your headline has failed.",
    headline: "Where Is Your Funnel Leaking Money? (Diagnostic Chart)",
    description: "Save This High-Resolution Diagnostic Flowchart",
    cta: "Download",
    creativeId: 'cr_img_11',
    creativeUrl: 'https://storage.googleapis.com/ad-analyser-assets/ankit_broken_funnel_chart.png',
    driveUrl: 'https://drive.google.com/file/d/1M3k9N7P2xYw_DemoBrokenFunnelChart/view?usp=sharing',
    landingPageUrl: 'https://ankitbatra.io/growth-accelerator?utm_source=meta&utm_content=v11_chart',
    tier: 'Promising',
    tierScore: 88,
    tierReasoning: [
      'High conversion rate (3.75%) and very low CPL (₹69.44)',
      'High CTR (3.50%) on low CPC (₹2.23)',
      'Needs scale from ₹1,250 to ₹6,000 to verify consistency across larger audience cohorts'
    ],
    evidence: [
      'Visual chart diagram acts as an immediate pattern interrupt in newsfeed',
      'Actionable diagnostic premise drives immediate high-intent clicks'
    ]
  },
  {
    clientId: 'client-ankit-batra',
    platform: 'meta',
    account: 'Ankit Batra Growth',
    campaign: 'MOFU_Retargeting_HighIntent_Q3',
    adSet: 'Website_Visitors_30d_VideoViewers_50pct',
    adName: 'AB_V12_ZeroSpend_NewUpload_Placeholder',
    adId: 'ad_90124812',
    date: '2026-09-18',
    objective: 'LEADS',
    spend: 0,
    impressions: 0,
    reach: 0,
    clicks: 0,
    ctr: 0,
    cpc: 0,
    cpm: 0,
    landingPageViews: 0,
    leads: 0,
    purchases: 0,
    conversions: 0,
    conversionRate: 0,
    cpl: 0,
    cpa: 0,
    revenue: 0,
    roas: 0,
    primaryText: "New creative variation testing 3-second founder hook with screen share.",
    headline: "How To Audit Your Meta Account in 15 Minutes",
    description: "New Sandbox Test Creative",
    cta: "Learn More",
    creativeId: 'cr_vid_12',
    tier: 'Insufficient Data',
    tierScore: 0,
    tierReasoning: ['Zero spend ad - newly uploaded / not yet approved or delivered by platform'],
    evidence: ['Requires platform delivery before evaluation']
  }
];

export const DEMO_CREATIVE_INTELLIGENCE: Record<string, CreativeIntelligence> = {
  ad_90124801: {
    adId: 'ad_90124801',
    adName: 'AB_V1_ProblemHook_StopWastingBudget_UGC',
    creativeType: 'video',
    format: 'UGC',
    durationSeconds: 42,
    hookType: 'Problem-led',
    hookFirst3Seconds: '"If your Meta CPA doubled this month, stop touching your bidding strategy..." (Handheld camera zoom in on frustrated expression)',
    mainAngle: 'pain_point',
    audiencePainPoint: 'Rising CPA and burning ad budget on untested variations',
    promise: 'Pinpoint the exact 3-second hook leak causing the CAC spike in under 10 minutes',
    offer: 'Free 1-on-1 Growth Blueprint Call with Ankit Batra',
    cta: 'Click Book Now below to claim one of 5 weekly founder slots',
    speaker: true,
    textOverlay: true,
    pacing: 'Fast',
    productRevealSeconds: 4,
    creativeStrengths: [
      'Immediate pattern interrupt in 0.8 seconds with bold red text overlay',
      'Pain point matches top objection of B2B founders scaling past ₹20k/day',
      'Clear, unpolished UGC aesthetic outperforms corporate slick ads by 3.2x',
      'Verbal hook matches primary headline verbatim'
    ],
    creativeWeaknesses: [
      'Call to action in final 5 seconds could reinforce the specific calendar availability urgency'
    ],
    transcript: 'If your Meta CPA doubled this month, stop touching your bidding strategy. In 90% of the 250+ client accounts we audited, the bleed isn\'t your targeting—it\'s your first 3 seconds. Here is the exact Creative-Led Funnel framework we use to generate high-intent B2B discovery calls under ₹120 consistently. Click below to book your audit.',
    visualHierarchyScore: 9,
    headlineClarityScore: 9,
    driveUrlStatus: 'public_accessible',
    thumbnailUrl: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=600&auto=format&fit=crop&q=80'
  },
  ad_90124802: {
    adId: 'ad_90124802',
    adName: 'AB_V2_FounderBreakdown_WhiteboardMath',
    creativeType: 'video',
    format: 'Founder',
    durationSeconds: 58,
    hookType: 'Contrarian',
    hookFirst3Seconds: '"Most agencies blame iOS updates. Let\'s write the real math on the board..." (Founder writing ₹800 CAC vs ₹40,000 deal size on physical whiteboard)',
    mainAngle: 'social_proof',
    audiencePainPoint: 'Agency excuses and lack of unit economic clarity',
    promise: 'Show step-by-step how higher-intent qualification cuts effective CAC in half',
    offer: 'Growth Blueprint Strategy Session',
    cta: 'Click Learn More to watch the complete 15-minute breakdown video',
    speaker: true,
    textOverlay: true,
    pacing: 'Moderate',
    productRevealSeconds: 3,
    creativeStrengths: [
      'Physical whiteboard creates extreme authority and educational curiosity',
      'Direct unit economics calculation builds logical trust with analytical founders',
      'Clean audio with crisp lavalier mic and no background music distraction'
    ],
    creativeWeaknesses: [
      'Video length (58s) is on the longer side; could test a trimmed 35s cut'
    ],
    transcript: 'Most agencies blame iOS updates or Meta algorithms when CAC spikes. Let\'s do the actual unit economics on a whiteboard: If your CAC is ₹800 and your average deal size is ₹40,000, you don\'t need cheaper traffic. You need higher-intent creative qualification. Watch how we restructured this exact B2B funnel.',
    visualHierarchyScore: 9,
    headlineClarityScore: 8,
    driveUrlStatus: 'public_accessible',
    thumbnailUrl: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=600&auto=format&fit=crop&q=80'
  },
  ad_90124806: {
    adId: 'ad_90124806',
    adName: 'AB_V6_Generic_GrowthMasterclass_StockVideo',
    creativeType: 'video',
    format: 'Motion Graphic',
    durationSeconds: 30,
    hookType: 'Direct Offer',
    hookFirst3Seconds: 'Generic smiling business people in glass boardroom with slow corporate stock animation',
    mainAngle: 'desire',
    audiencePainPoint: 'Vague desire to grow business',
    promise: 'Scale your revenue with digital marketing',
    offer: 'Online masterclass registration',
    cta: 'Sign Up Now',
    speaker: false,
    textOverlay: true,
    pacing: 'Deliberate',
    productRevealSeconds: 15,
    creativeStrengths: [
      'Clean typography and 1080p video rendering'
    ],
    creativeWeaknesses: [
      'Zero pattern interrupt; looks like a generic insurance or bank ad',
      'No human face speaking or authentic founder connection',
      'Delayed product reveal (15s); 80% of viewers bounce before knowing the offer',
      'Vague, clichéd claims with no tangible proof or numbers'
    ],
    transcript: 'Join our exclusive growth masterclass to learn proven strategies to scale your revenue and master digital marketing across all channels in 2026. Register today for the online session.',
    visualHierarchyScore: 4,
    headlineClarityScore: 3,
    driveUrlStatus: 'public_accessible',
    thumbnailUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=600&auto=format&fit=crop&q=80'
  },
  ad_90124808: {
    adId: 'ad_90124808',
    adName: 'AB_V8_MismatchedLP_ScalePast50k_OfferDiscount',
    creativeType: 'image',
    format: 'Static High-Contrast',
    hookType: 'Direct Offer',
    hookFirst3Seconds: '90% Off Template Pack with bright yellow discount sticker',
    mainAngle: 'urgency_pricing',
    audiencePainPoint: 'Want quick templates without high consulting cost',
    promise: 'Instant download 50 swipe templates for ₹499',
    offer: '90% Off Templates',
    cta: 'Get Offer',
    speaker: false,
    textOverlay: true,
    pacing: 'Fast',
    productRevealSeconds: 1,
    creativeStrengths: [
      'High visual contrast and bold discount badge driving cheap CTR'
    ],
    creativeWeaknesses: [
      'FATAL MESSAGE MISMATCH: Ad promises ₹499 instant templates, but landing page asks user to book a 45-minute growth consultation call',
      'Attracts low-intent bargain hunters who bounce immediately on high-ticket consultation LP'
    ],
    visualHierarchyScore: 6,
    headlineClarityScore: 4,
    driveUrlStatus: 'public_accessible',
    thumbnailUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&auto=format&fit=crop&q=80'
  }
};

export const DEMO_LANDING_PAGE_ANALYSIS: LandingPageAnalysis = {
  url: 'https://ankitbatra.io/growth-accelerator',
  headline: 'Double Your B2B Pipeline & Cut Meta CAC In Half With Creative-Led Funnels',
  subheadline: 'An 8-Week Implementation Accelerator for Founders & CMOs Doing >$20k MRR. We Build & Audit Your Entire Creative-Testing Machine.',
  mainOffer: 'Book a 1-on-1 Growth Blueprint Call ($500 Value, Free for Qualified B2B Teams)',
  cta: 'Schedule Your 1-on-1 Growth Blueprint Call',
  aboveFoldClarityScore: 9,
  benefitsIdentified: [
    'Direct 1-on-1 weekly creative teardowns with Ankit Batra',
    'Custom Figma & CapCut hook templates tested across ₹12Cr spend',
    'Live dashboard tracking Hook Rate, Hold Rate, and CPA attribution',
    'Full access to 250+ winning ad swipe library'
  ],
  proofElements: [
    'Audited ₹12Cr+ in ad spend badge with client logos (DevScale, HyperGrowth, SaaSFlow)',
    'Video testimonials from 6 verified B2B founders with before/after CAC charts',
    'Case study breakdowns with actual Meta Ads Manager screenshots'
  ],
  objectionsAddressed: [
    '"Will this work for high-ticket service vs SaaS?" (Addressed in FAQ section)',
    '"Do we need in-house video editors?" (Templates and plug-and-play workflow provided)',
    '"What if we don\'t see results?" (100% money-back conditional sprint guarantee)'
  ],
  formFrictionScore: 'Low',
  messageMatchScore: 8.8,
  messageMatchFeedback: 'Strong message match with problem-led and whiteboard ads (AB_V1, AB_V2, AB_V9). Severe mismatch with template discount ad (AB_V8).',
  alignmentChain: {
    adHook: 'Why Your B2B Ads Bleed Cash (And The 3-Second Fix)',
    adPromise: 'Pinpoint the exact 3-second hook leak and cut CAC',
    lpHeadline: 'Double Your B2B Pipeline & Cut Meta CAC In Half With Creative-Led Funnels',
    lpOffer: 'Free 1-on-1 Growth Blueprint Call for Qualified Founders',
    conversionFriction: 'Multi-step qualification form filters unqualified traffic effectively without excessive drop-off.'
  },
  recommendedCROFixes: [
    'Add a 2-minute founder video snippet directly next to the calendar widget above the fold',
    'Display timezone switcher prominently to prevent drop-offs from US/EU prospects',
    'Create a separate dedicated landing page for static infographic checklist downloads'
  ]
};

export const DEMO_EXPERIMENTS: ExperimentItem[] = [
  {
    id: 'exp-01',
    clientId: 'client-ankit-batra',
    title: 'Problem-Led Hook vs Contrarian Math Hook',
    hypothesis: 'Problem-led hook in first 2 seconds will achieve >3.2% CTR and reduce CPL below ₹100 compared to contrarian math hook.',
    variable: 'Hook',
    kpi: 'CPL',
    status: 'Winner',
    baselineMetric: '₹145 CPL',
    targetMetric: '< ₹110 CPL',
    currentResult: '₹99.19 CPL (31.6% improvement)',
    startDate: '2026-09-01',
    learnings: 'Problem-led hook (AB_V1) drove 186 leads at ₹99.19 CPL and 5.04x ROAS, proving superior in top-of-funnel broad audiences.'
  },
  {
    id: 'exp-02',
    clientId: 'client-ankit-batra',
    title: 'Static Diagnostic Chart vs Video UGC in Retargeting',
    hypothesis: 'High-contrast diagnostic chart will reduce fatigue and lower retargeting CPL by 20% vs repeating video UGC.',
    variable: 'Visual Format',
    kpi: 'Conversion Rate',
    status: 'Running',
    baselineMetric: '2.4% CVR',
    targetMetric: '> 3.2% CVR',
    currentResult: '3.09% CVR (₹115.25 CPL)',
    startDate: '2026-09-10',
    learnings: 'Early data shows 3.09% conversion rate with strong initial ROAS of 4.34x.'
  },
  {
    id: 'exp-03',
    clientId: 'client-ankit-batra',
    title: 'Scale "Audited ₹12Cr" Numbers Hook to Broad',
    hypothesis: 'Testing high-authority spend numbers in hook (AB_V9) will scale efficiently from sandbox to ₹20k/day campaign.',
    variable: 'Hook',
    kpi: 'ROAS',
    status: 'Planned',
    baselineMetric: '3.2x ROAS',
    targetMetric: '> 4.5x ROAS',
    startDate: '2026-09-22',
    learnings: 'Sandbox test showed 7.84x preliminary ROAS with ₹63.79 CPL on ₹1,850 spend. Ready for scale phase.'
  },
  {
    id: 'exp-04',
    clientId: 'client-ankit-batra',
    title: 'Dedicated Micro-Landing Page for Checklist Download',
    hypothesis: 'Direct 1-field email opt-in page for infographic will achieve >18% conversion rate vs sending traffic to call booking page.',
    variable: 'LP Headline',
    kpi: 'Conversion Rate',
    status: 'Planned',
    baselineMetric: '3.09% CVR',
    targetMetric: '> 15.0% CVR',
    startDate: '2026-09-25'
  }
];

export const DEMO_HISTORICAL_RUNS: HistoricalAnalysisRun[] = [
  {
    id: 'run-sep-18',
    clientId: 'client-ankit-batra',
    timestamp: '2026-09-18 16:30:00',
    dateRangeLabel: 'Last 7 Days (12 Sep - 18 Sep 2026)',
    totalSpend: 70620,
    totalRevenue: 248000,
    roas: 3.51,
    totalConversions: 574,
    topWinningHook: 'Problem-led ("If your Meta CPA doubled this month...")',
    keyFinding: 'UGC Problem-led video and Whiteboard math generated 55% of all qualified pipeline; Stock video and template discount ads caused 80% of wasted budget.',
    winningPatternsCount: 3,
    experimentsLaunched: 4
  },
  {
    id: 'run-sep-04',
    clientId: 'client-ankit-batra',
    timestamp: '2026-09-04 11:15:00',
    dateRangeLabel: 'Previous Period (28 Aug - 04 Sep 2026)',
    totalSpend: 62400,
    totalRevenue: 198000,
    roas: 3.17,
    totalConversions: 420,
    topWinningHook: 'Contrarian Math ("Let\'s do the actual unit economics...")',
    keyFinding: 'Whiteboard format established baseline authority; recommended testing problem-led raw UGC variations.',
    winningPatternsCount: 2,
    experimentsLaunched: 3
  }
];

export const DEMO_AD_RECORDS_MKR: UnifiedAdRecord[] = [
  {
    clientId: 'client-mkr-audit',
    platform: 'manual',
    account: 'BMX Media Account',
    campaign: 'BMX | MKR | CBO | Max conv value | 10/09/26',
    adSet: 'MKR-77+78+79 Scaling Group',
    adName: 'MKR-77 (Winner Static/Video Cluster)',
    adId: 'ad_mkr_77',
    date: '2026-09-28',
    objective: 'SALES',
    spend: 2385.46,
    impressions: 8417,
    reach: 7200,
    clicks: 67,
    ctr: 0.80,
    cpc: 35.60,
    cpm: 283.41,
    landingPageViews: 58,
    leads: 0,
    purchases: 9,
    conversions: 9,
    conversionRate: 15.52,
    cpl: 0,
    cpa: 265.05,
    revenue: 4491,
    roas: 1.88,
    primaryText: 'High converting direct response creative cluster MKR-77.',
    headline: 'MKR-77 Winner Offer',
    description: 'Scaled acquisition creative',
    cta: 'Shop Now',
    tier: 'Strong Performer',
    tierScore: 94,
    tierReasoning: [
      'Exceptional CPA of ₹265.05 (68% cheaper than account average ₹833)',
      'Delivered 1.88x ROAS with steady 9 sales on ₹2,385 spend',
      'Primary scale candidate to absorb budget from fatigued ads'
    ],
    evidence: [
      'Highest conversion efficiency in the entire CBO campaign',
      'Stable performance with strong purchase velocity'
    ]
  },
  {
    clientId: 'client-mkr-audit',
    platform: 'manual',
    account: 'BMX Media Account',
    campaign: 'BMX | MKR | CBO | Max conv value | 10/09/26',
    adSet: 'MKR-77+78+79 Scaling Group',
    adName: 'MKR-78 (Winner Static/Video Cluster)',
    adId: 'ad_mkr_78',
    date: '2026-09-28',
    objective: 'SALES',
    spend: 2385.46,
    impressions: 8417,
    reach: 7200,
    clicks: 67,
    ctr: 0.80,
    cpc: 35.60,
    cpm: 283.41,
    landingPageViews: 58,
    leads: 0,
    purchases: 9,
    conversions: 9,
    conversionRate: 15.52,
    cpl: 0,
    cpa: 265.05,
    revenue: 4491,
    roas: 1.88,
    primaryText: 'High converting direct response creative cluster MKR-78.',
    headline: 'MKR-78 Winner Variation',
    description: 'Scaled acquisition creative',
    cta: 'Shop Now',
    tier: 'Strong Performer',
    tierScore: 94,
    tierReasoning: [
      'Tied for lowest CPA in account at ₹265.05',
      'Generated ₹4,491 revenue at 1.88x ROAS',
      'Ready for immediate budget increase'
    ]
  },
  {
    clientId: 'client-mkr-audit',
    platform: 'manual',
    account: 'BMX Media Account',
    campaign: 'BMX | MKR | ABO |LP2| Master campaign| 18-sep-26',
    adSet: 'ABO Retargeting & High Intent',
    adName: 'MKR_AB_VS-32(DP) - (DP) MKR_AB_VS_1x1',
    adId: 'ad_mkr_vs_32_dp',
    date: '2026-09-28',
    objective: 'SALES',
    spend: 222.38,
    impressions: 564,
    reach: 510,
    clicks: 9,
    ctr: 1.60,
    cpc: 24.71,
    cpm: 394.29,
    landingPageViews: 8,
    leads: 0,
    purchases: 2,
    conversions: 2,
    conversionRate: 25.0,
    cpl: 0,
    cpa: 111.19,
    revenue: 998,
    roas: 4.49,
    primaryText: 'High CTR 1x1 angle with breakout click-through rate.',
    headline: 'MKR_AB_VS-32(DP) Breakout Star',
    description: 'Highest ROAS ad in account',
    cta: 'Learn More',
    tier: 'Strong Performer',
    tierScore: 96,
    tierReasoning: [
      'Account-high 4.49x ROAS with lowest CPA of ₹111.19',
      'Exceptional CTR of 1.60% (2x account average of 0.81%)',
      'Severely under-allocated: Received only ₹222 spend'
    ]
  },
  {
    clientId: 'client-mkr-audit',
    platform: 'manual',
    account: 'BMX Media Account',
    campaign: 'BMX | MKR | ABO |LP2| Master campaign| 03-sep-26',
    adSet: 'ABO Master AdSet',
    adName: 'MKR_AB_VS-56 (H&F)',
    adId: 'ad_mkr_vs_56',
    date: '2026-09-28',
    objective: 'SALES',
    spend: 575.58,
    impressions: 1988,
    reach: 1750,
    clicks: 13,
    ctr: 0.65,
    cpc: 44.28,
    cpm: 289.53,
    landingPageViews: 11,
    leads: 0,
    purchases: 2,
    conversions: 2,
    conversionRate: 18.18,
    cpl: 0,
    cpa: 287.79,
    revenue: 998,
    roas: 1.73,
    primaryText: 'Health & Fitness angle creative MKR-56.',
    headline: 'MKR-56 Health & Fitness',
    description: 'Strong ROAS performer',
    cta: 'Order Now',
    tier: 'Promising',
    tierScore: 84,
    tierReasoning: ['Solid 1.73x ROAS and low ₹287.79 CPA', 'Good candidate for progressive scale']
  },
  {
    clientId: 'client-mkr-audit',
    platform: 'manual',
    account: 'BMX Media Account',
    campaign: 'BMX | MKR | CBO | Max conv value | 10/09/26',
    adSet: 'Potential Videos Cohort',
    adName: 'potential videos - MKR_AB_VS_41 (B)',
    adId: 'ad_mkr_vs_41_cbo',
    date: '2026-09-28',
    objective: 'SALES',
    spend: 2443.73,
    impressions: 10382,
    reach: 8900,
    clicks: 78,
    ctr: 0.75,
    cpc: 31.33,
    cpm: 235.38,
    landingPageViews: 65,
    leads: 0,
    purchases: 8,
    conversions: 8,
    conversionRate: 12.31,
    cpl: 0,
    cpa: 305.47,
    revenue: 3992,
    roas: 1.63,
    primaryText: 'Potential videos cohort creative MKR-41.',
    headline: 'MKR-41 Potential Winner',
    description: '1.63x ROAS scale candidate',
    cta: 'Shop Now',
    tier: 'Strong Performer',
    tierScore: 88,
    tierReasoning: [
      'Strong 1.63x ROAS with 8 sales at ₹305.47 CPA',
      'Consistent buyer volume in CBO stack'
    ]
  },
  {
    clientId: 'client-mkr-audit',
    platform: 'manual',
    account: 'BMX Media Account',
    campaign: 'BMX | MKR | CBO | Max conv value | 10/09/26',
    adSet: 'MKR-77+78+79 Scaling Group',
    adName: 'MKR-79',
    adId: 'ad_mkr_79',
    date: '2026-09-28',
    objective: 'SALES',
    spend: 2382.42,
    impressions: 9187,
    reach: 8100,
    clicks: 62,
    ctr: 0.67,
    cpc: 38.43,
    cpm: 259.33,
    landingPageViews: 52,
    leads: 0,
    purchases: 5,
    conversions: 5,
    conversionRate: 9.62,
    cpl: 0,
    cpa: 476.48,
    revenue: 2495,
    roas: 1.05,
    primaryText: 'Direct response creative MKR-79.',
    headline: 'MKR-79 Variant',
    description: 'Break-even creative in winning cluster',
    cta: 'Shop Now',
    tier: 'Average',
    tierScore: 72
  },
  {
    clientId: 'client-mkr-audit',
    platform: 'manual',
    account: 'BMX Media Account',
    campaign: 'BMX | MKR | ABO |LP2| Master campaign| 03-sep-26',
    adSet: 'ABO Master AdSet',
    adName: 'MKR_AB_VS-55',
    adId: 'ad_mkr_vs_55',
    date: '2026-09-28',
    objective: 'SALES',
    spend: 3503.46,
    impressions: 14353,
    reach: 12200,
    clicks: 89,
    ctr: 0.62,
    cpc: 39.36,
    cpm: 158.78,
    landingPageViews: 74,
    leads: 0,
    purchases: 7,
    conversions: 7,
    conversionRate: 9.46,
    cpl: 0,
    cpa: 500.49,
    revenue: 3493,
    roas: 1.00,
    primaryText: 'Video static variation MKR-55.',
    headline: 'MKR-55 Acquisition Creative',
    description: 'Break-even performance',
    cta: 'Shop Now',
    tier: 'Average',
    tierScore: 68
  },
  {
    clientId: 'client-mkr-audit',
    platform: 'manual',
    account: 'BMX Media Account',
    campaign: 'BMX | MKR | CBO | Max conv value | 10/09/26',
    adSet: 'Old Winners Cohort',
    adName: 'old winners(VS-AI3,7,19,36,27) - MKR_AI Video_2',
    adId: 'ad_mkr_ai_vid_2',
    date: '2026-09-28',
    objective: 'SALES',
    spend: 2343.77,
    impressions: 5274,
    reach: 4600,
    clicks: 52,
    ctr: 0.99,
    cpc: 45.07,
    cpm: 444.40,
    landingPageViews: 44,
    leads: 0,
    purchases: 4,
    conversions: 4,
    conversionRate: 9.09,
    cpl: 0,
    cpa: 585.94,
    revenue: 1996,
    roas: 0.85,
    primaryText: 'AI generated video variation 2 from old winners cluster.',
    headline: 'MKR AI Video 2',
    description: 'Sub-1.0x ROAS performer',
    cta: 'Learn More',
    tier: 'Average',
    tierScore: 62
  },
  {
    clientId: 'client-mkr-audit',
    platform: 'manual',
    account: 'BMX Media Account',
    campaign: 'BMX | MKR | ABO |LP2| Master campaign| 03-sep-26',
    adSet: 'ABO Master AdSet',
    adName: 'MKR_AB_VS- 50 (White Board)',
    adId: 'ad_mkr_vs_50_wb',
    date: '2026-09-28',
    objective: 'SALES',
    spend: 4862.76,
    impressions: 20255,
    reach: 17100,
    clicks: 191,
    ctr: 0.94,
    cpc: 25.46,
    cpm: 296.47,
    landingPageViews: 160,
    leads: 0,
    purchases: 6,
    conversions: 6,
    conversionRate: 3.75,
    cpl: 0,
    cpa: 810.46,
    revenue: 2994,
    roas: 0.62,
    primaryText: 'Whiteboard style explainer video for MKR.',
    headline: 'MKR White Board Explainer',
    description: 'High CPA bleeder',
    cta: 'Learn More',
    tier: 'Underperforming',
    tierScore: 48,
    tierReasoning: ['High CPA of ₹810.46 on ₹4,862 spend', 'Poor conversion rate on landing page (3.75%)']
  },
  {
    clientId: 'client-mkr-audit',
    platform: 'manual',
    account: 'BMX Media Account',
    campaign: 'BMX | MKR | CBO | Max conv value | 10/09/26',
    adSet: 'Winner Videos Stack (Fatigued)',
    adName: 'MKR-73 (winner videos+statics)',
    adId: 'ad_mkr_73',
    date: '2026-09-28',
    objective: 'SALES',
    spend: 26159.10,
    impressions: 98566,
    reach: 78000,
    clicks: 786,
    ctr: 0.80,
    cpc: 33.28,
    cpm: 265.40,
    landingPageViews: 650,
    leads: 0,
    purchases: 32,
    conversions: 32,
    conversionRate: 4.92,
    cpl: 0,
    cpa: 817.47,
    revenue: 15968,
    roas: 0.61,
    primaryText: 'Top historically spending creative suffering from deep audience fatigue.',
    headline: 'MKR-73 Historical Winner',
    description: 'High spend fatigue bleeder',
    cta: 'Shop Now',
    tier: 'Underperforming',
    tierScore: 42,
    tierReasoning: [
      'Critical account budget bleed: Consumed 40% of entire budget (₹26,159) at 0.61x ROAS',
      'High CPA of ₹817.47 is far above account target',
      'Urgent recommendation: Throttle daily budget by 60% and redirect to MKR-77/78'
    ]
  },
  {
    clientId: 'client-mkr-audit',
    platform: 'manual',
    account: 'BMX Media Account',
    campaign: 'BMX_MKR_CBO_AT - 19/09/26',
    adSet: 'Winner Videos Stack (Fatigued)',
    adName: 'MKR-74 (winner videos+statics)',
    adId: 'ad_mkr_74',
    date: '2026-09-28',
    objective: 'SALES',
    spend: 7184.39,
    impressions: 22292,
    reach: 18400,
    clicks: 195,
    ctr: 0.87,
    cpc: 36.84,
    cpm: 333.12,
    landingPageViews: 160,
    leads: 0,
    purchases: 8,
    conversions: 8,
    conversionRate: 5.0,
    cpl: 0,
    cpa: 898.05,
    revenue: 3992,
    roas: 0.56,
    primaryText: 'MKR-74 winner video static stack in secondary CBO.',
    headline: 'MKR-74 Historical Winner',
    description: '0.56x ROAS bleeder',
    cta: 'Shop Now',
    tier: 'Underperforming',
    tierScore: 38,
    tierReasoning: ['High CPA of ₹898.05 with negative unit economics', 'Recommend pausing or capping spend']
  },
  {
    clientId: 'client-mkr-audit',
    platform: 'manual',
    account: 'BMX Media Account',
    campaign: 'BMX | MKR | CBO | Max conv value | 10/09/26',
    adSet: 'White Board Cohort',
    adName: 'MKR_AB_VS- 51 (White Board)',
    adId: 'ad_mkr_vs_51_wb',
    date: '2026-09-28',
    objective: 'SALES',
    spend: 3226.96,
    impressions: 8157,
    reach: 6900,
    clicks: 60,
    ctr: 0.74,
    cpc: 53.78,
    cpm: 395.61,
    landingPageViews: 48,
    leads: 0,
    purchases: 3,
    conversions: 3,
    conversionRate: 6.25,
    cpl: 0,
    cpa: 1075.65,
    revenue: 1497,
    roas: 0.46,
    primaryText: 'Whiteboard format test 51.',
    headline: 'MKR-51 Whiteboard',
    description: 'High CPA bleeder (₹1,075 CPA)',
    cta: 'Learn More',
    tier: 'Underperforming',
    tierScore: 34
  },
  {
    clientId: 'client-mkr-audit',
    platform: 'manual',
    account: 'BMX Media Account',
    campaign: 'BMX | MKR | ABO |LP2| Master campaign| 03-sep-26',
    adSet: 'ABO Master AdSet',
    adName: 'MKR_AB_VS- 52B',
    adId: 'ad_mkr_vs_52b',
    date: '2026-09-28',
    objective: 'SALES',
    spend: 3274.64,
    impressions: 13427,
    reach: 11100,
    clicks: 125,
    ctr: 0.93,
    cpc: 26.20,
    cpm: 243.88,
    landingPageViews: 102,
    leads: 0,
    purchases: 0,
    conversions: 0,
    conversionRate: 0,
    cpl: 0,
    cpa: 0,
    revenue: 0,
    roas: 0,
    primaryText: 'Variation 52B with zero sales generated.',
    headline: 'MKR-52B Zero Sale Bleeder',
    description: '100% budget loss',
    cta: 'Shop Now',
    tier: 'Underperforming',
    tierScore: 15,
    tierReasoning: [
      'Complete budget loss: ₹3,274.64 spent with ZERO sales (#DIV/0!)',
      'Immediate action: Kill ad immediately to stop negative cash drain'
    ]
  },
  {
    clientId: 'client-mkr-audit',
    platform: 'manual',
    account: 'BMX Media Account',
    campaign: 'BMX | MKR | CBO | Max conv value | 10/09/26',
    adSet: 'Low Spend Videos Group',
    adName: 'low spend videos - MKR_AB_VS_50 (B)',
    adId: 'ad_mkr_low_spend',
    date: '2026-09-28',
    objective: 'SALES',
    spend: 3020.56,
    impressions: 8893,
    reach: 7600,
    clicks: 76,
    ctr: 0.85,
    cpc: 39.74,
    cpm: 339.66,
    landingPageViews: 62,
    leads: 0,
    purchases: 2,
    conversions: 2,
    conversionRate: 3.23,
    cpl: 0,
    cpa: 1510.28,
    revenue: 998,
    roas: 0.33,
    primaryText: 'Low spend videos stack ad.',
    headline: 'MKR Low Spend Group',
    description: 'High CPA bleeder (₹1,510 CPA)',
    cta: 'Learn More',
    tier: 'Underperforming',
    tierScore: 24
  },
  {
    clientId: 'client-mkr-audit',
    platform: 'manual',
    account: 'BMX Media Account',
    campaign: 'BMX | MKR | ABO |LP2| Master campaign| 03-sep-26',
    adSet: 'ABO Master AdSet',
    adName: 'MKR_AB_VS-54',
    adId: 'ad_mkr_vs_54',
    date: '2026-09-28',
    objective: 'SALES',
    spend: 2457.93,
    impressions: 5024,
    reach: 4300,
    clicks: 32,
    ctr: 0.64,
    cpc: 76.81,
    cpm: 489.24,
    landingPageViews: 26,
    leads: 0,
    purchases: 2,
    conversions: 2,
    conversionRate: 7.69,
    cpl: 0,
    cpa: 1228.97,
    revenue: 998,
    roas: 0.41,
    primaryText: 'Variation 54 high CPA creative.',
    headline: 'MKR-54 Ad Variant',
    description: '0.41x ROAS bleeder',
    cta: 'Shop Now',
    tier: 'Underperforming',
    tierScore: 28
  },
  {
    clientId: 'client-mkr-audit',
    platform: 'manual',
    account: 'BMX Media Account',
    campaign: 'BMX | MKR | ABO |LP2| Master campaign| 03-sep-26',
    adSet: 'ABO Master AdSet',
    adName: 'MKR_AB_VS-57',
    adId: 'ad_mkr_vs_57',
    date: '2026-09-28',
    objective: 'SALES',
    spend: 1428.90,
    impressions: 3278,
    reach: 2800,
    clicks: 24,
    ctr: 0.73,
    cpc: 59.54,
    cpm: 435.91,
    landingPageViews: 19,
    leads: 0,
    purchases: 1,
    conversions: 1,
    conversionRate: 5.26,
    cpl: 0,
    cpa: 1428.90,
    revenue: 499,
    roas: 0.35,
    primaryText: 'Variation 57 underperforming creative.',
    headline: 'MKR-57 Variant',
    description: 'High CPA bleeder (₹1,428)',
    cta: 'Shop Now',
    tier: 'Underperforming',
    tierScore: 26
  },
  {
    clientId: 'client-mkr-audit',
    platform: 'manual',
    account: 'BMX Media Account',
    campaign: 'BMX | MKR | ABO |LP2| Master campaign| 18-sep-26',
    adSet: 'ABO Secondary AdSet',
    adName: 'MKR_AB_VS-41 (ABO)',
    adId: 'ad_mkr_vs_41_abo',
    date: '2026-09-28',
    objective: 'SALES',
    spend: 856.42,
    impressions: 2608,
    reach: 2200,
    clicks: 31,
    ctr: 1.19,
    cpc: 27.63,
    cpm: 328.38,
    landingPageViews: 25,
    leads: 0,
    purchases: 1,
    conversions: 1,
    conversionRate: 4.0,
    cpl: 0,
    cpa: 856.42,
    revenue: 499,
    roas: 0.58,
    primaryText: 'MKR-41 ABO test ad.',
    headline: 'MKR-41 ABO Variant',
    description: 'Sub-optimal performance in ABO',
    cta: 'Shop Now',
    tier: 'Underperforming',
    tierScore: 36
  },
  {
    clientId: 'client-mkr-audit',
    platform: 'manual',
    account: 'BMX Media Account',
    campaign: 'BMX | MKR | ABO |LP2| Master campaign| 18-sep-26',
    adSet: 'ABO Micro Tests',
    adName: 'MKR_AB_VS-32(RK) - (Ranveer) MKR_AB_VS_32_1x1',
    adId: 'ad_mkr_vs_32_rk',
    date: '2026-09-28',
    objective: 'SALES',
    spend: 140.19,
    impressions: 402,
    reach: 360,
    clicks: 1,
    ctr: 0.25,
    cpc: 140.19,
    cpm: 348.73,
    landingPageViews: 1,
    leads: 0,
    purchases: 0,
    conversions: 0,
    conversionRate: 0,
    cpl: 0,
    cpa: 0,
    revenue: 0,
    roas: 0,
    primaryText: 'Low spend Ranveer test ad.',
    headline: 'MKR-32 RK Test',
    description: 'Insufficient spend to determine viability',
    cta: 'Learn More',
    tier: 'Insufficient Data',
    tierScore: 40
  },
  {
    clientId: 'client-mkr-audit',
    platform: 'manual',
    account: 'BMX Media Account',
    campaign: 'BMX | MKR | CBO | Max conv value | 10/09/26',
    adSet: 'Whiteboard Micro Tests',
    adName: 'MKR_AB_VS- 42 (White Board)',
    adId: 'ad_mkr_vs_42_wb',
    date: '2026-09-28',
    objective: 'SALES',
    spend: 115.69,
    impressions: 251,
    reach: 220,
    clicks: 1,
    ctr: 0.40,
    cpc: 115.69,
    cpm: 460.92,
    landingPageViews: 1,
    leads: 0,
    purchases: 0,
    conversions: 0,
    conversionRate: 0,
    cpl: 0,
    cpa: 0,
    revenue: 0,
    roas: 0,
    primaryText: 'Micro spend whiteboard ad.',
    headline: 'MKR-42 Test',
    description: 'Insufficient spend',
    cta: 'Learn More',
    tier: 'Insufficient Data',
    tierScore: 40
  }
];
